[package]
name = "utp"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
log = "0.4.22"
bytes = "1.9.0"
env_logger = "0.11.6"
chrono = "0.4.39"
colored = "2.2.0"
futures = "0.3.31"
